version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-pulse_dwh}
      - POSTGRES_USER=${POSTGRES_USER:-pulse_admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pulse_secret}
    ports:
      - "5432:5432"

  airflow-init:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-pulse_admin}:${POSTGRES_PASSWORD:-pulse_secret}@postgres:5432/${POSTGRES_DB:-pulse_dwh}
    depends_on:
      - postgres
    command: version

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-pulse_admin}:${POSTGRES_PASSWORD:-pulse_secret}@postgres:5432/${POSTGRES_DB:-pulse_dwh}
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-pulse_admin}:${POSTGRES_PASSWORD:-pulse_secret}@postgres:5432/${POSTGRES_DB:-pulse_dwh}
    command: scheduler
